# Generated by Django 2.2.10 on 2021-12-29 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quizapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=512, verbose_name='возможный вариант ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=128, verbose_name='название опроса')),
                ('quiz_description', models.CharField(max_length=4000, verbose_name='описание опроса')),
                ('start_date', models.DateTimeField(default=quizapp.models.get_default_start_date, verbose_name='дата начала опроса')),
                ('end_date', models.DateTimeField(default=quizapp.models.get_default_end_date, verbose_name='дата окончания опроса')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=4000, verbose_name='текстовый ответ пользователя')),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='кто ответил')),
                ('possible_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.PossibleAnswer', verbose_name='вариант ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiestion_text', models.CharField(max_length=512, verbose_name='текст вопроса')),
                ('question_type', models.PositiveSmallIntegerField(choices=[(1, 'текстовый'), (2, 'выбор одного варианта'), (3, 'выбор нескольких вариантов')], default=2, verbose_name='тип вопроса')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Quiz', verbose_name='опрос')),
            ],
        ),
        migrations.AddField(
            model_name='possibleanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.Question', verbose_name='вопрос'),
        ),
    ]
